// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlyloo7E5kadSqzXudxKy_e_a3zuudnjg',
    appId: '1:320285086131:web:d0b29a8eb779068af07bc6',
    messagingSenderId: '320285086131',
    projectId: 'jbm-escpos-database',
    authDomain: 'jbm-escpos-database.firebaseapp.com',
    storageBucket: 'jbm-escpos-database.firebasestorage.app',
    measurementId: 'G-D92FRJZ8T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqi4Drts40naPDfE9JS2MfimLzeQ3cUc',
    appId: '1:320285086131:android:dd06b826bf4eb3d1f07bc6',
    messagingSenderId: '320285086131',
    projectId: 'jbm-escpos-database',
    storageBucket: 'jbm-escpos-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARpOcXTIOJxZKdv3ZYmM-C4aSxECJnfEU',
    appId: '1:320285086131:ios:88b75deb9c0037e4f07bc6',
    messagingSenderId: '320285086131',
    projectId: 'jbm-escpos-database',
    storageBucket: 'jbm-escpos-database.firebasestorage.app',
    iosBundleId: 'com.example.jbmEscpos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARpOcXTIOJxZKdv3ZYmM-C4aSxECJnfEU',
    appId: '1:320285086131:ios:88b75deb9c0037e4f07bc6',
    messagingSenderId: '320285086131',
    projectId: 'jbm-escpos-database',
    storageBucket: 'jbm-escpos-database.firebasestorage.app',
    iosBundleId: 'com.example.jbmEscpos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlyloo7E5kadSqzXudxKy_e_a3zuudnjg',
    appId: '1:320285086131:web:a0612b421b494499f07bc6',
    messagingSenderId: '320285086131',
    projectId: 'jbm-escpos-database',
    authDomain: 'jbm-escpos-database.firebaseapp.com',
    storageBucket: 'jbm-escpos-database.firebasestorage.app',
    measurementId: 'G-CP184044ME',
  );

}